announce = false
debug = true
description = 'Development Server'
gamemode = 'Development'
host = '0.0.0.0'
language = 'de'
modules = [ 'js-module', 'js-bytecode-module' ]
name = 'Test-Server'
players = 100
port = 7788
resources = [
    #Basic
    'chat',
    'freeroam',
    'noclip',
    'tuner',
    'speedometer',
]